### ISSUE TITLE
Update to v2023.10.0

### ISSUE THREAD

**Issue by pinpox** [regnat/pretix-nix#2]
Any chance this could be updated to the current version? [v2023.10.0](https://github.com/pretix/pretix/releases/tag/v2023.10.0)

**Comment by thufschmitt** [comment]
Hi,

I'm not really using or maintaining this any more. @n0emis seems to have a more active fork that might be worth checking out.

I'll archive this repo to clear the confusion. @n0emis (or any one), I can also link to your fork if you intend to maintain it further
